#ifndef AUDIOMINIAUDIOCONFIG_H
#define AUDIOMINIAUDIOCONFIG_H

#ifdef ESP_PLATFORM
#define MA_NO_DEVICE_IO
#define MA_NO_ENCODING
#define MA_NO_RESOURCE_MANAGER
#define MA_NO_NODE_GRAPH
#define MA_NO_ENGINE
#define MA_NO_RUNTIME_LINKING
#define MA_NO_THREADING
#endif

#endif // AUDIOMINIAUDIOCONFIG_H
